image: docker:git

variables:
  REGISTRY_URI: "${REGISTRY_DOMAIN}/clario-web/w2a-next"
  REGISTRY_DOMAIN: "${REGISTRY_ID}.dkr.ecr.us-east-1.amazonaws.com"
  IMAGE_VERSION: 1.0.$CI_PIPELINE_ID
  IMAGE_FULL_PATH: $REGISTRY_URI:$CI_PIPELINE_ID
  IMAGE_LATEST_PATH: $REGISTRY_URI:latest
  IMAGE_STABLE_PATH: $REGISTRY_URI:stable
  REGION: us-east-1

stages:
  - build
  - deploy

## ===== build templates =====
.before_script_templates:
  before_script: &install_aws_cli
    - apk add aws-cli --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
    - apk --upgrade --no-cache add curl && apk --update add python3 py3-pip groff less mailcap openssl && apk --purge del py3-pip && rm /var/cache/apk/*
    - update-ca-certificates
# ===== build templates end =====

## ===== build =====
.build-image:
  stage: build
  before_script: *install_aws_cli
  after_script:
    - docker logout
  script:
    - docker build -f ./Dockerfile -t $IMAGE_FULL_PATH --build-arg VERSION=$IMAGE_VERSION --build-arg GITLAB_DEPENDENCY_KEY="$GITLAB_DEPENDENCY_KEY" .
    - aws --profile testing ecr get-login-password --region "${REGION}" | docker login --username AWS --password-stdin "${REGISTRY_DOMAIN}"
    - docker push $IMAGE_FULL_PATH
  when: manual
  tags:
    - aws-runner
    - us-east-1

build-image-testing:
  extends: .build-image
  environment:
    name: testing

build-image-staging:
  extends: .build-image
  environment:
    name: staging

## ===== build end =====

## ===== deploy =====
.deploy:
  stage: deploy
  before_script: *install_aws_cli
  script:
    - aws --profile testing ecr get-login-password --region "${REGION}" | docker login --username AWS --password-stdin "${REGISTRY_DOMAIN}"
    - docker tag $IMAGE_FULL_PATH $IMAGE_LATEST_PATH
    - docker push $IMAGE_LATEST_PATH
    - aws --profile testing ecs update-service --cluster clario-web --service w2a-next --force-new-deployment --region "${REGION}"
    - aws --profile testing ecs wait services-stable --cluster clario-web --services w2a-next --region "${REGION}"
    - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths "/*"
  when: manual
  tags:
    - aws-runner
    - us-east-1

deploy testing:
  extends: .deploy
  environment:
    name: testing
    url: https://next.tz.clario.co/ping
  needs: [ "build-image-testing" ]
  dependencies:
    - build-image-testing

deploy staging:
  extends: .deploy
  environment:
    name: staging
    url: https://next.sz.clario.co/ping
  needs: [ "build-image-staging" ]
  dependencies:
    - build-image-staging

## ===== deploy end =====
