image: docker:git

variables:
  GITLAB_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID
  REGISTRY_DOMAIN: "${REGISTRY_ID}.dkr.ecr.us-east-1.amazonaws.com"
  REGISTRY_URI: "${REGISTRY_DOMAIN}/clario-web/w2a-next"
  IMAGE_VERSION: 1.0.$CI_PIPELINE_ID
  IMAGE_FULL_PATH: $REGISTRY_URI:$CI_PIPELINE_ID
  IMAGE_LATEST_PATH: $REGISTRY_URI:latest
  IMAGE_STABLE_PATH: $REGISTRY_URI:stable
  REGION: us-east-1

stages:
  - build
  - deploy

## ===== build templates =====
.before_script_templates:
  before_script: &install_aws_cli
    - apk add aws-cli --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
    - apk --upgrade --no-cache add curl && apk --update add python3 py3-pip groff less mailcap openssl && apk --purge del py3-pip && rm /var/cache/apk/*
    - update-ca-certificates
# ===== build templates end =====

## ===== build =====
build-image:
  stage: build
  before_script: *install_aws_cli
  after_script:
    - docker logout
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f ./Dockerfile --pull --build-arg VERSION=$CI_PIPELINE_IID -t $GITLAB_REGISTRY_IMAGE .
    - docker push $GITLAB_REGISTRY_IMAGE
  when: always
  environment:
    name: testing
  tags:
    - aws-runner
    - us-east-1

## ===== build end =====

## ===== deploy =====
deploy testing:
  stage: deploy
  before_script: *install_aws_cli
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $GITLAB_REGISTRY_IMAGE
    - aws --profile testing ecr get-login-password --region "${REGION}" | docker login --username AWS --password-stdin "${REGISTRY_DOMAIN}"
    - docker tag $GITLAB_REGISTRY_IMAGE $IMAGE_LATEST_PATH
    - docker push $IMAGE_LATEST_PATH
    - aws --profile testing ecs update-service --cluster clario-web --service w2a-next --force-new-deployment --region "${REGION}"
    - aws --profile testing ecs wait services-stable --cluster clario-web --services w2a-next --region "${REGION}"
    - aws --profile testing cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths "/*"
  when: manual
  tags:
    - aws-runner
    - us-east-1
  environment:
    name: testing
    url: https://next.tz.clario.co/next/api/ping
  needs: ['build-image']

deploy staging:
  stage: deploy
  before_script: *install_aws_cli
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $GITLAB_REGISTRY_IMAGE
    - aws --profile staging ecr get-login-password --region "${REGION}" | docker login --username AWS --password-stdin "${REGISTRY_DOMAIN}"
    - docker tag $GITLAB_REGISTRY_IMAGE $IMAGE_LATEST_PATH
    - docker push $IMAGE_LATEST_PATH
    - aws --profile staging ecs update-service --cluster clario-web --service w2a-next --force-new-deployment --region "${REGION}"
    - aws --profile staging ecs wait services-stable --cluster clario-web --services w2a-next --region "${REGION}"
    - aws --profile staging cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths "/*"
  when: manual
  tags:
    - aws-runner
    - us-east-1
  environment:
    name: staging
    url: https://next.sz.clario.co/next/api/ping
  needs: ['build-image']


deploy production:
  stage: deploy
  before_script: *install_aws_cli
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $GITLAB_REGISTRY_IMAGE
    - aws --profile production ecr get-login-password --region "${REGION}" | docker login --username AWS --password-stdin "${REGISTRY_DOMAIN}"
    - docker tag $GITLAB_REGISTRY_IMAGE $IMAGE_LATEST_PATH
    - docker push $IMAGE_LATEST_PATH
    - aws --profile production ecs update-service --cluster clario-web --service w2a-next --force-new-deployment --region "${REGION}"
    - aws --profile production ecs wait services-stable --cluster clario-web --services w2a-next --region "${REGION}"
    - aws --profile production cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths "/*"
  when: manual
  tags:
    - aws-runner
    - us-east-1
  environment:
    name: staging
    url: https://next.clario.co/next/api/ping
  needs: ['build-image']
  only:
    - main

## ===== deploy end =====
