export enum TypographyComponents {
    h1 = 'h1',
    h2 = 'h2',
    h3 = 'h3',
    h4 = 'h4',
    h5 = 'h5',
    h6 = 'h6',
    p = 'p',
    div = 'div',
    span = 'span',
}

export enum TypographyVariants {
    huge = 'huge',
    h1 = 'h1',
    h2 = 'h2',
    h3 = 'h3',
    h4 = 'h4',
    h5 = 'h5',
    h6 = 'h6',
    p1 = 'p1',
    p2 = 'p2',
    p3 = 'p3',
    p4 = 'p4',
    p5 = 'p5',
    span1 = 'span1',
    span2 = 'span2',
    span3 = 'span3',
    span4 = 'span4',
    span5 = 'span5',
}
